name: baap ka raaj h

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '*/30 * * * *'

jobs:
  heavy-processing:
    runs-on: soul
    
    strategy:
      matrix:
        job_num: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Make scripts executable
        run: chmod +x *
      
      - name: attack command
        run: python3 SOULCRACK.py
